import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

metadata = sa.MetaData()

nsfw_video_jobs = sa.Table(
    "nsfw_video_jobs",
    metadata,
    sa.Column("job_id", sa.Text(), primary_key=True),
    sa.Column("video_id", sa.Text(), nullable=False),
    sa.Column("source_object_version", sa.Text(), nullable=False, server_default=""),
    sa.Column("policy_version", sa.Text(), nullable=False),
    sa.Column("status", sa.Text(), nullable=False),
    sa.Column("publisher_user_id", sa.Text(), nullable=False),
    sa.Column("post_id", sa.Text()),
    sa.Column("canister_id", sa.Text()),
    sa.Column("source_video_uri", sa.Text(), nullable=False),
    sa.Column("upload_event_id", sa.Text()),
    sa.Column("trace_id", sa.Text()),
    sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
    sa.Column("last_error_code", sa.Text()),
    sa.Column("last_error_message", sa.Text()),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    sa.Column("started_at", sa.DateTime(timezone=True)),
    sa.Column("finished_at", sa.DateTime(timezone=True)),
    sa.UniqueConstraint("video_id", "source_object_version", "policy_version"),
)

_severity_columns = (
    "overall_severity",
    "safe_severity",
    "suggestive_severity",
    "nudity_severity",
    "porn_severity",
    "gore_severity",
    "violence_severity",
    "self_harm_severity",
    "hate_or_extremism_severity",
    "drugs_severity",
    "unknown_severity",
    "sexual_minor_content_severity",
)

nsfw_frame_results = sa.Table(
    "nsfw_frame_results",
    metadata,
    sa.Column("frame_id", sa.Text(), primary_key=True),
    sa.Column("job_id", sa.Text(), sa.ForeignKey("nsfw_video_jobs.job_id", ondelete="CASCADE"), nullable=False),
    sa.Column("video_id", sa.Text(), nullable=False),
    sa.Column("frame_index", sa.Integer(), nullable=False),
    sa.Column("frame_timestamp_seconds", sa.Double(), nullable=False),
    sa.Column("frame_hash", sa.Text()),
    sa.Column("prompt_version", sa.Text(), nullable=False),
    sa.Column("model_provider", sa.Text(), nullable=False),
    sa.Column("model_name", sa.Text(), nullable=False),
    sa.Column("model_version", sa.Text()),
    sa.Column("top_category", sa.Text(), nullable=False),
    sa.Column("is_nsfw", sa.Boolean(), nullable=False),
    *(sa.Column(column, sa.SmallInteger(), nullable=False) for column in _severity_columns),
    sa.Column("reason", sa.Text(), nullable=False),
    sa.Column("raw_response", postgresql.JSONB(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    sa.UniqueConstraint("job_id", "frame_index"),
    *(sa.CheckConstraint(f"{column} BETWEEN 0 AND 5") for column in _severity_columns),
)

nsfw_video_results = sa.Table(
    "nsfw_video_results",
    metadata,
    sa.Column("job_id", sa.Text(), sa.ForeignKey("nsfw_video_jobs.job_id", ondelete="CASCADE"), primary_key=True),
    sa.Column("video_id", sa.Text(), nullable=False),
    sa.Column("policy_version", sa.Text(), nullable=False),
    sa.Column("prompt_version", sa.Text(), nullable=False),
    sa.Column("aggregation_version", sa.Text(), nullable=False),
    sa.Column("final_is_nsfw", sa.Boolean(), nullable=False),
    sa.Column("final_score", sa.Double(), nullable=False),
    sa.Column("final_top_category", sa.Text(), nullable=False),
    sa.Column("max_overall_severity", sa.SmallInteger(), nullable=False),
    sa.Column("nsfw_frame_count", sa.Integer(), nullable=False),
    sa.Column("total_frame_count", sa.Integer(), nullable=False),
    sa.Column("move_required", sa.Boolean(), nullable=False),
    sa.Column("move_threshold", sa.Double(), nullable=False),
    sa.Column("legacy_nsfw_ec", sa.Text(), nullable=False),
    sa.Column("legacy_nsfw_gore", sa.Text(), nullable=False),
    sa.Column("final_response", postgresql.JSONB(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
)

nsfw_storage_actions = sa.Table(
    "nsfw_storage_actions",
    metadata,
    sa.Column("action_id", sa.Text(), primary_key=True),
    sa.Column("job_id", sa.Text(), sa.ForeignKey("nsfw_video_jobs.job_id", ondelete="CASCADE"), nullable=False),
    sa.Column("video_id", sa.Text(), nullable=False),
    sa.Column("publisher_user_id", sa.Text(), nullable=False),
    sa.Column("action_type", sa.Text(), nullable=False),
    sa.Column("threshold", sa.Double(), nullable=False),
    sa.Column("final_score", sa.Double(), nullable=False),
    sa.Column("request_url", sa.Text(), nullable=False),
    sa.Column("request_body", postgresql.JSONB(), nullable=False),
    sa.Column("response_status", sa.Integer()),
    sa.Column("response_body", sa.Text()),
    sa.Column("status", sa.Text(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    sa.Column("completed_at", sa.DateTime(timezone=True)),
)

