SERVICE_HEADER = "x-yral-service"
TIMESTAMP_HEADER = "x-yral-timestamp"
NONCE_HEADER = "x-yral-nonce"
SIGNATURE_HEADER = "x-yral-signature"

SIGNED_REQUEST_HEADERS = (
    SERVICE_HEADER,
    TIMESTAMP_HEADER,
    NONCE_HEADER,
    SIGNATURE_HEADER,
)

