CREATE TABLE IF NOT EXISTS yral.video_nsfw_detection
(
    video_id String,
    job_id String,
    publisher_user_id String,
    post_id Nullable(String),
    canister_id Nullable(String),
    source_video_uri String,
    source_object_version String,
    upload_event_id Nullable(String),
    status LowCardinality(String),
    policy_version String,
    prompt_version String,
    aggregation_version String,
    model_provider LowCardinality(String),
    model_name String,
    model_version Nullable(String),
    duration_seconds Float32,
    frames_extracted UInt32,
    frames_processed UInt32,
    frame_batch_size UInt8,
    final_is_nsfw UInt8,
    final_score Float32,
    final_top_category LowCardinality(String),
    max_overall_severity UInt8,
    nsfw_frame_count UInt32,
    total_frame_count UInt32,
    max_suggestive_severity UInt8,
    max_nudity_severity UInt8,
    max_porn_severity UInt8,
    max_gore_severity UInt8,
    max_violence_severity UInt8,
    max_self_harm_severity UInt8,
    max_hate_or_extremism_severity UInt8,
    max_drugs_severity UInt8,
    max_unknown_severity UInt8,
    max_sexual_minor_content_severity UInt8,
    move_required UInt8,
    move_threshold Float32,
    storj_move_status LowCardinality(String),
    legacy_nsfw_ec LowCardinality(String),
    legacy_nsfw_gore LowCardinality(String),
    frame_results_json String,
    final_response_json String,
    created_at DateTime64(3, 'UTC'),
    updated_at DateTime64(3, 'UTC'),
    _updated_at DateTime64(3, 'UTC')
)
ENGINE = ReplacingMergeTree(_updated_at)
PARTITION BY toYYYYMM(created_at)
ORDER BY (video_id, policy_version, source_object_version);

